### ISSUE TITLE
vite marked as peerDependency but uses direct import from vite

### ISSUE THREAD

**Issue by MarZab** [aleclarson/vite-tsconfig-paths#161]
vite [is used](https://github.com/aleclarson/vite-tsconfig-paths/commit/e7ccfe6465d0a265d582e5bb83a7cc894121b4bc#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R8) as a direct dependancy in the project but marked as only a peer in `package.json`. 

The issue materialises itself with using `yarn` with `nodeLinker: pnpm` that has strict package dependency resolution.

The temporary fix is to mark vite as a dependancy in `.yarnrc.yml`

```yaml
nodeLinker: pnpm

packageExtensions:
  "vite-tsconfig-paths@*":
    dependencies:
      vite: "*"

```
